# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: azhivaeva
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: ase-assessment-task
# "service" is the name of this project. This will also be added to your AWS resource names.
service: ase-assessment-task

provider:
  name: aws
  runtime: nodejs20.x
  httpApi:
    cors: true

functions:
  recommendation-api:
    handler: src/lambda.handler
    events:
      - httpApi: '*'
